spring:
  application:
    name: yu-agent
  ai:
    dashscope:
      api-key: 'your key sk-'
      chat:
        options:
          model: qwen-plus
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
        enabled: true
        request-timeout: 30s
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.rain.yuagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# Search API 配置
search-api:
  api-key: ''
# 配置Spring AI日志输出为 debug
logging:
  level:
    org.springframework.ai: debug

